dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt-get install texlive-full

script:
  - ./build.sh build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
